version = "1.0.0.1"
version_code = "250509.1"
changelog = """修复了250509（发布于2025/5/9）中的一个因为配置文件引起的bug。
这个bug会导致程序无法启动且没有任何错误信息。"""
date = "20250509"
importance = "low"
file_name = "EECT_1.0.0.1.250509.1.-windows-x64.zip"
download_url = "hhttps://github.com/Lyang1273/data/raw/refs/heads/main/%E4%B8%BB%E9%A2%98%E5%9B%BE%E7%89%87.zip"
