version = "1.0.0.1"
version_code = "250509.1"
changelog = """修复了250509（发布于2025/5/9）中的一个因为配置文件引起的bug。
这个bug会导致程序无法启动且没有任何错误信息。"""
date = "20250509"
importance = "low"
file_name = "131232.zip"
download_url = "https://bgithub.xyz/Lyang1273/data/raw/refs/heads/main/131232.zip"
proxy_url = "https://ghfast.top/https://github.com/EECT/EECT/releases/download/v1.0.0.1/EECT_1.0.0.1.250509.1.-windows-x64.zip"
